### ISSUE TITLE
升级新版本后，发现自定义卡片里sensor.xxx_x_usage报错了，应该是属性里的水表数格式变了导致的

### ISSUE THREAD

**Issue by x2rr** [WeiYang1982/bj_water#3]
<img width="561" alt="image" src="https://github.com/WeiYang1982/bj_water/assets/23189213/eaa87a3d-9146-4f9e-945c-a184efe5db81">

之前是数字格式，现在变成- - '127'这种格式了，导致报错了

```
type: custom:flex-table-card
title: 用水情况
entities:
  include: sensor.xxx_*_usage
  exclude: sensor.xxx_total_usage
columns:
  - name: 月份
    data: name
  - name: 用水量
    data: 总用水量
    suffix: m³
  - name: 水表数
    data: 水表数
    suffix: m³
```
